import { StyleSheet } from 'react-native';
import { goldTint } from '../../../utils/colorHelpers';

/**
 * Creates the Home screen stylesheet.
 * Accepts the current theme colors and dark-mode flag so the
 * styles react to theme changes (identical visuals to the
 * original inline StyleSheet.create).
 */
export function createHomeStyles(C: any, isDark: boolean) {
  const gt = (alpha: number) => goldTint(alpha, C);

  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: C.background.primary,
    },
    container: {
      flex: 1,
      paddingHorizontal: 12,
      paddingTop: 0,
      // Reduced bottom padding now that tab bar height adapts; prevents stretched feel
      paddingBottom: 70,
      backgroundColor: 'transparent',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 2,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: C.text.primary,
      flex: 1,
    },
    headerButtons: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingRight: 0,
      flexShrink: 0,
      zIndex: 10,
      elevation: 3,
    },
    refreshButton: {
      backgroundColor: `${C.surface.secondary}CC`,
      padding: 6,
      borderRadius: 20,
      marginRight: 6,
      borderWidth: 1,
      borderColor: C.border.light,
    },
    rotating: { transform: [{ rotate: '45deg' }] },
    donateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: C.accent.gold,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 16,
      minWidth: 140,
    },
    donateText: {
      color: C.text.inverse,
      marginLeft: 8,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 8,
      backgroundColor: `${C.surface.secondary}AA`,
      borderBottomWidth: 1,
      borderBottomColor: `${C.border.light}80`,
    },
    locationText: {
      color: C.text.primary,
      marginLeft: 8,
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.5,
      textTransform: 'capitalize',
    },
    dateNav: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: `${C.surface.elevated}88`,
      borderBottomWidth: 1,
      borderBottomColor: `${C.border.light}60`,
    },
    navButton: {
      padding: 4,
      borderRadius: 20,
      backgroundColor: C.surface.secondary,
      borderWidth: 1,
      borderColor: C.border.light,
    },
    dateText: {
      color: C.text.primary,
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: C.background.primary,
    },
    loadingText: {
      color: C.text.secondary,
      marginTop: 16,
      fontSize: 16,
      letterSpacing: 0.5,
    },
    scrollView: { flex: 1, width: '100%' },
    scrollViewContent: { paddingHorizontal: 8, paddingBottom: 120 },
    dateContainer: {
      marginVertical: 6,
      borderRadius: 16,
      overflow: 'hidden',
      // Light mode: use warmer background
      backgroundColor: isDark ? `${C.surface.primary}DD` : `${C.background.secondary}DD`,
    },
    dateInnerContainer: {
      padding: 8,
      alignItems: 'center',
      // Light mode: use warmer background
      backgroundColor: isDark ? `${C.surface.elevated}BB` : `${C.background.tertiary}BB`,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: `${C.border.accent}60`,
    },
    gregorianDate: {
      color: C.text.primary,
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    hijriDate: {
      color: C.text.secondary,
      fontSize: 12,
      marginTop: 4,
      fontWeight: '400',
      letterSpacing: 0.5,
    },
    countdownContainer: {
      padding: 12,
      alignItems: 'center',
      // Light mode: use warmer background
      backgroundColor: isDark ? C.surface.primary : C.background.secondary,
      margin: 12,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: C.border.medium,
    },
    nextPrayerText: {
      color: C.text.primary,
      fontSize: 16,
      textAlign: 'center',
      letterSpacing: 0.5,
      fontWeight: '500',
    },
    nextPrayerTime: {
      color: C.accent.gold,
      fontSize: 26,
      fontWeight: 'bold',
      marginVertical: 6,
      textAlign: 'center',
      letterSpacing: 1,
    },
    countdownText: {
      color: C.text.primary,
      fontSize: 42,
      fontWeight: '300',
      letterSpacing: 2,
      textAlign: 'center',
    },
    timesContainer: { paddingHorizontal: 4, paddingVertical: 10 },
    prayerItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 16,
      // Light mode: use warmer background
      backgroundColor: isDark ? `${C.surface.primary}CC` : `${C.background.secondary}CC`,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: `${C.border.light}80`,
    },
    nextPrayerItem: {
      backgroundColor: `${C.special.highlight}EE`,
      borderWidth: 0.5,
      borderColor: C.accent.gold,
    },
    prayerNameContainer: { flexDirection: 'row', alignItems: 'center' },
    iconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: C.surface.secondary,
      borderWidth: 1,
      borderColor: C.border.medium,
    },
    prayerName: {
      color: C.text.primary,
      fontSize: 16,
      marginLeft: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
    },
    prayerTime: {
      color: C.accent.gold,
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    circularCountdownContainer: {
      alignItems: 'center',
      backgroundColor: C.surface.transparent,
      borderWidth: 1,
      borderColor: C.border.light,
    },
    progressCenter: {
      position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
      justifyContent: 'center', alignItems: 'center', padding: 10,
    },
    footer: {
      marginTop: 24, marginBottom: 16, alignItems: 'center', paddingVertical: 12,
      borderTopWidth: 1, borderTopColor: C.border.light,
    },
    modalOverlay: {
      flex: 1, backgroundColor: `${C.text.primary}70`, justifyContent: 'center', alignItems: 'center', padding: 20,
    },
    modalContent: {
      width: '90%', backgroundColor: C.surface.elevated, borderRadius: 16, borderWidth: 1,
      borderColor: C.border.medium, overflow: 'hidden', maxHeight: '70%',
    },
    modalHeader: {
      flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
      padding: 16, borderBottomWidth: 1, borderBottomColor: C.border.light,
    },
    modalTitle: { color: C.text.primary, fontSize: 20, fontWeight: 'bold', letterSpacing: 0.5 },
    regionItem: {
      flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
      padding: 16, borderBottomWidth: 1, borderBottomColor: C.border.light,
    },
    selectedRegionItem: { backgroundColor: C.special.highlight },
    regionName: { color: C.text.primary, fontSize: 18, letterSpacing: 0.5 },
    selectedRegionName: { color: C.accent.gold, fontWeight: 'bold' },
    dropdownIcon: { marginLeft: 'auto', marginRight: 10 },
    settingsButton: {
      backgroundColor: C.surface.secondary, padding: 10, borderRadius: 20, marginRight: 10,
      borderWidth: 0.5, borderColor: C.border.light,
    },
    countdownLoading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 6 },
    countdownLoadingText: { color: C.text.secondary, fontSize: 16, marginLeft: 6, opacity: 0.8 },
    languageButton: {
      backgroundColor: C.surface.secondary, padding: 8, borderRadius: 20, marginRight: 4,
      borderWidth: 0.5, borderColor: C.border.light, alignItems: 'center', justifyContent: 'center', width: 36, height: 36,
    },
    languageItem: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16,
      borderBottomWidth: 1, borderBottomColor: C.border.light,
    },
    selectedLanguageItem: { backgroundColor: C.special.highlight },
    languageName: { color: C.text.primary, fontSize: 18, letterSpacing: 0.5 },
    selectedLanguageName: { color: C.accent.gold, fontWeight: 'bold' },
    contentContainer: { flex: 1, width: '100%', backgroundColor: 'transparent' },
    progressIndicatorText: {
      color: C.accent.gold, fontSize: 12, marginTop: 4, fontWeight: '500', letterSpacing: 0.5, opacity: 0.8,
    },
    sparkle: { position: 'absolute', zIndex: 1 },
    magicalHeader: {
      position: 'relative', paddingVertical: 8, paddingHorizontal: 12, marginBottom: 0, borderRadius: 20,
      backgroundColor: 'transparent', borderWidth: 0, borderColor: 'transparent',
      // REMOVED: overflow: 'hidden' - this was blocking touch events on Android
    },
    headerGlow: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: C.accent.gold, borderRadius: 20 },
    headerStar: { position: 'absolute', zIndex: 2 },
    magicalFooter: {
      position: 'relative', paddingVertical: 15, paddingHorizontal: 20, marginTop: 20, marginBottom: 10, borderRadius: 20,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)',
      borderWidth: 0.5, borderColor: isDark ? gt(0.1) : gt(0.2), overflow: 'hidden',
    },
    footerShimmer: { position: 'absolute', top: 0, bottom: 0, width: 100, backgroundColor: 'transparent' },
    footerElement: { position: 'absolute', zIndex: 2 },
    footerContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', zIndex: 3, position: 'relative' },
    footerMoon: { marginRight: 10 },
    footerText: { color: C.text.secondary, fontSize: 14, fontWeight: '500', letterSpacing: 0.5, textAlign: 'center', flex: 1 },
    footerStar: { marginLeft: 10 },
    enhancedCircularContainer: { alignItems: 'center', justifyContent: 'center', marginVertical: 20, position: 'relative' },
    circularGlow: { position: 'absolute', backgroundColor: C.accent.gold, opacity: 0.05 },
    circularProgress: { position: 'relative', zIndex: 2 },
    circularContent: { position: 'absolute', alignItems: 'center', justifyContent: 'center', zIndex: 3 },
    nextPrayerLabel: { color: C.text.tertiary, fontSize: 12, marginBottom: 4, fontWeight: '500', letterSpacing: 1, textTransform: 'uppercase' },
    nextPrayerName: { color: C.text.primary, fontSize: 20, fontWeight: 'bold', marginBottom: 4, letterSpacing: 0.5 },
    countdown: { color: C.accent.gold, fontSize: 18, fontWeight: '600', marginTop: 8, letterSpacing: 0.5, textAlign: 'center', minHeight: 22 },
    activeIconContainer: { backgroundColor: C.special.highlight },
    activePrayerName: { color: C.accent.darkGold, fontWeight: 'bold' },
    activePrayerTime: { color: C.accent.amber, fontWeight: 'bold', fontSize: 18 },
    buttonShimmer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(255,220,140,0.15)', borderRadius: 8 },
    headerSection: { marginBottom: 8 },
    enhancedLocationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : C.surface.secondary,
      borderRadius: 16,
      paddingVertical: 10,
      paddingHorizontal: 18,
      marginTop: 0,
      borderWidth: 0.5,
      borderColor: isDark ? gt(0.2) : C.border.light,
    },
    locationIconWrapper: {
      width: 36, height: 36, borderRadius: 18, backgroundColor: gt(0.1), alignItems: 'center', justifyContent: 'center', marginRight: 12,
    },
    locationTextWrapper: { flex: 1 },
    locationLabel: { color: C.text.tertiary, fontSize: 12, fontWeight: '500', letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 2 },
    locationActionWrapper: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
    dateNavigationSection: { marginBottom: 8 },
    enhancedDateNav: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      // Light mode: use background.secondary for warmth instead of pure white
      backgroundColor: isDark ? 'rgba(255,255,255,0.024)' : C.background.secondary,
      borderRadius: 20,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderWidth: 0.5,
      borderColor: isDark ? gt(0.15) : C.border.medium,
    },
    dateDisplayContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
    primaryDateText: { color: C.text.primary, fontSize: 18, fontWeight: '700', letterSpacing: 0.5, textAlign: 'center' },
    secondaryDateText: { color: C.text.secondary, fontSize: 13, fontWeight: '500', letterSpacing: 0.3, textAlign: 'center', marginTop: 2, opacity: 0.8 },
    hijriDateText: { color: C.accent.amber, fontSize: 11, fontWeight: '400', letterSpacing: 0.2, textAlign: 'center', marginTop: 1, opacity: 0.9 },
    enhancedContentContainer: { flex: 1, backgroundColor: 'transparent' },
    enhancedLoadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
    loadingIconWrapper: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)', borderRadius: 30, padding: 20, marginBottom: 20,
      borderWidth: 0.5, borderColor: gt(0.2),
    },
    enhancedLoadingText: { color: C.text.primary, fontSize: 16, fontWeight: '600', textAlign: 'center', marginBottom: 8, letterSpacing: 0.3 },
    loadingSubtext: { color: C.text.secondary, fontSize: 14, textAlign: 'center', opacity: 0.7, letterSpacing: 0.2 },
    enhancedScrollView: { flex: 1 },
    enhancedScrollViewContent: { paddingBottom: 40 },
    enhancedDateContainer: {
      // Light mode: use subtle warm tint instead of black overlay
      backgroundColor: isDark ? 'rgba(255,255,255,0.048)' : C.background.tertiary,
      borderRadius: 16, marginBottom: 12, borderWidth: 0.5,
      borderColor: isDark ? gt(0.15) : C.border.light, overflow: 'hidden',
    },
    dateCardContent: { padding: 12 },
    gregorianDateSection: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
    enhancedGregorianDate: { color: C.text.primary, fontSize: 14, fontWeight: '600', marginLeft: 8, letterSpacing: 0.3 },
    hijriDateSection: { flexDirection: 'row', alignItems: 'center' },
    enhancedHijriDate: { color: C.text.secondary, fontSize: 12, fontWeight: '500', marginLeft: 8, letterSpacing: 0.2, opacity: 0.9 },
    countdownSection: { alignItems: 'center', marginBottom: 15 },
    enhancedTimesContainer: {
      // Light mode: use background.secondary for warmth instead of pure white
      backgroundColor: isDark ? 'rgba(255,255,255,0.032)' : C.background.secondary,
      borderRadius: 20,
      padding: 12,
      marginBottom: 12,
      borderWidth: 0.5,
      borderColor: isDark ? gt(0.15) : C.border.medium,
    },
    timesHeader: {
      flexDirection: 'row', alignItems: 'center', marginBottom: 10, paddingBottom: 8, borderBottomWidth: 0.5,
      borderBottomColor: gt(0.15),
    },
    timesHeaderText: { color: C.text.primary, fontSize: 18, fontWeight: '700', marginLeft: 10, letterSpacing: 0.5 },
    prayerTimesGrid: { gap: 8 },
    enhancedPrayerItem: {
      // Light mode: use background.tertiary for subtle card distinction
      backgroundColor: isDark ? 'rgba(255,255,255,0.024)' : C.background.tertiary,
      borderRadius: 16,
      padding: 10,
      borderWidth: 0.5,
      borderColor: isDark ? gt(0.1) : C.border.light,
      position: 'relative',
      overflow: 'hidden',
    },
    enhancedNextPrayerItem: {
      backgroundColor: isDark ? gt(0.06) : `${C.special.highlight}CC`,
      borderColor: isDark ? gt(0.25) : C.border.accent,
    },
    prayerItemHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
    enhancedIconContainer: {
      width: 40, height: 40, borderRadius: 20, backgroundColor: gt(0.08), alignItems: 'center', justifyContent: 'center',
      marginRight: 12, borderWidth: 0.5, borderColor: gt(0.15)
    },
    activeEnhancedIconContainer: { backgroundColor: gt(0.15), borderColor: gt(0.3) },
    enhancedPrayerName: { color: C.text.primary, fontSize: 16, fontWeight: '600', letterSpacing: 0.3, flex: 1 },
    activeEnhancedPrayerName: { color: C.accent.darkGold, fontWeight: '700' },
    prayerTimeWrapper: { alignItems: 'flex-end' },
    enhancedPrayerTime: { color: C.text.primary, fontSize: 18, fontWeight: '600', letterSpacing: 0.5, textAlign: 'right' },
    activeEnhancedPrayerTime: { color: C.accent.amber, fontWeight: '700', fontSize: 20 },
    nextIndicator: {
      flexDirection: 'row', alignItems: 'center', marginTop: 2, backgroundColor: gt(0.12),
      paddingHorizontal: 8, paddingVertical: 1, borderRadius: 10,
    },
    nextIndicatorText: { color: C.accent.darkGold, fontSize: 10, fontWeight: '600', marginLeft: 4, letterSpacing: 0.5, textTransform: 'uppercase' },
    returnToTodayButton: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
      paddingVertical: 6, paddingHorizontal: 14, marginTop: 6,
      borderRadius: 16, backgroundColor: gt(0.10),
      alignSelf: 'center',
    },
    returnToTodayText: {
      color: C.accent.gold, fontSize: 12, fontWeight: '600', marginLeft: 5, letterSpacing: 0.3,
    },
    iqamaFooterContainer: {
      flexDirection: 'row', alignItems: 'flex-start', marginTop: 10, marginBottom: 4,
      paddingHorizontal: 4, gap: 5,
    },
    iqamaFooterText: {
      color: C.text.secondary, fontSize: 11, fontWeight: '400', opacity: 0.65, flex: 1, lineHeight: 15,
    },
    // Compact header additions
    compactHeaderWrapper: {
      marginBottom: 8,
      paddingHorizontal: 4,
      gap: 6,
    },
    compactHeaderTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    compactLocationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 1,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: isDark ? 'rgba(255,255,255,0.044)' : C.surface.secondary,
      borderRadius: 14,
      gap: 6,
      borderWidth: 0.5,
      borderColor: isDark ? gt(0.2) : C.border.light,
      minWidth: 120,
      maxWidth: '55%',
    },
    compactLocationText: {
      flex: 1,
      color: C.text.primary,
      fontSize: 13,
      fontWeight: '500',
    },
    compactDateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      // Light mode: use warmer background instead of pure white
      backgroundColor: isDark ? 'rgba(255,255,255,0.036)' : C.background.secondary,
      borderRadius: 16,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderWidth: 0.5,
      borderColor: isDark ? gt(0.15) : C.border.medium,
      gap: 8,
    },
    compactDateCenter: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
  });
}
